services:
  development:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=development
    ports:
      - 5432:5432
    volumes:
      - ./scripts/000-schemas.sql:/docker-entrypoint-initdb.d/000-schemas.sql
      - ./scripts/001-seed.sql:/docker-entrypoint-initdb.d/001-seed.sql

  test:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - 5433:5432
    volumes:
      - ./scripts/000-schemas.sql:/docker-entrypoint-initdb.d/000-schemas.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 7777:8080
